import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillYoutube
} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Akmal Firmansyah Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-2 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>DEVELOPEDBYAF</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={function(){setDarkMode(!darkMode);}} className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md text-white ml-8' href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-6'>
            <h2 className='text-4xl text-teal-600 font-medium py-1 md:text-6xl'>
              Akmal Fransisco
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>
              Developer and Designer.
            </h3>
            <p className='text-md text-gray-800 py-5 leading-8 md:text-xl max-w-md mx-auto dark:text-white'>
              Freelancer providing services for programming and design content needs. Join me down below and let's get cracking!
            </p>
          </div>
          <div className='text-5xl text-gray-600 py-3 flex justify-center gap-16 dark:text-white'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:w-96 md:h-96 mb-12'>
            <Image src={deved} alt='' layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
          <h3 className="text-3xl font-bold py-1 dark:text-white ">
            Services I offer
          </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className='md:flex gap-4 mx-auto'>
            <div className='text-center shadow-xl p-10 rounded-xl my-10 md:max-w-sm lg:max-w-md dark:bg-white'>
              <Image className='mx-auto' alt='' src={design} width={100} height={100} />
              <h3 className='text-lg font-bold pt-8 pb-2'>
                Beautiful Designs hehe
              </h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core design theory.
              </p>
              <h4 className='text-teal-500 py-4 font-medium'>
                Design tools I use :
              </h4>
              <p className='text-gray-800 py-1'>
                Photoshop
              </p>
              <p className='text-gray-800 py-1'>
                Ilustrator
              </p>
              <p className='text-gray-800 py-1'>
                Figma
              </p>
            </div>
            <div className='text-center shadow-xl p-10 rounded-xl my-10 md:max-w-sm lg:max-w-md dark:bg-white'>
              <Image className='mx-auto' src={code} alt='' width={100} height={100} />
              <h3 className='text-lg font-bold pt-8 pb-2'>
                Code your dream project
              </h3>
              <p className='py-2'>
                Do you have an idea for your next great website? Let's make it a reality.
              </p>
              <h4 className='text-teal-500 py-4 font-medium'>
                Design tools I use :
              </h4>
              <p className='text-gray-800 py-1'>
                Photoshop
              </p>
              <p className='text-gray-800 py-1'>
                Ilustrator
              </p>
              <p className='text-gray-800 py-1'>
                Figma
              </p>
            </div>
            <div className='text-center shadow-xl p-10 rounded-xl my-10 md:max-w-sm lg:max-w-md dark:bg-white'>
              <Image className='mx-auto' src={consulting} alt='' width={100} height={100} />
              <h3 className='text-lg font-bold pt-8 pb-2'>
                Consulting
              </h3>
              <p className='py-2'>
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className='text-teal-500 py-4 font-medium'>
                Design tools I use :
              </h4>
              <p className='text-gray-800 py-1'>
                Photoshop
              </p>
              <p className='text-gray-800 py-1'>
                Ilustrator
              </p>
              <p className='text-gray-800 py-1'>
                Figma
              </p>
            </div>
          </div>
        </section>
          
        <section>
        <div>
            <h3 className='text-3xl font-bold py-1 dark:text-white'>
              Portofolio
            </h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover' 
                width={100} 
                height={100} 
                layout='responsive' 
                src={web1} 
                alt=''/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
                className='rounded-lg object-cover' 
                width={100} 
                height={100} 
                layout='responsive' 
                src={web2} 
                alt=''/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
                className='rounded-lg object-cover' 
                width={100} 
                height={100} 
                layout='responsive' 
                src={web3} 
                alt=''/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
                className='rounded-lg object-cover' 
                width={100} 
                height={100} 
                layout='responsive' 
                src={web4} 
                alt=''/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover' 
                width={100} 
                height={100} 
                layout='responsive' 
                src={web5} 
                alt=''/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
                className='rounded-lg object-cover' 
                width={100} 
                height={100} 
                layout='responsive' 
                src={web6} 
                alt=''/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
